language: c
script: make
compiler:
- clang
- gcc
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libusb-1.0-0-dev
env:
  global:
  - secure: CtAND8k/8Lfs6o4dmrD9Jp4yLjLQRrv5TZA1MkhSO/LRfViKlbzy7ENv1/ku0xgtnsegFRDFY75/dLHxZUiax5TGNVrHqpkkGSE9h2a5YYHxbOtINb8Hdzk+S2/EN9YPmrOEX1ZjMg/wH08c3MntdW6gDUuddQhjCuaNnH+8fUc=
  - secure: foN6qnWGy6p47PEutfZtUYUcg3DVHtuY3hfODDLDjc3TF7w7W9p/Mf/w4u++rkLuoKu/hESoiyj7/bSePx98EJgXsDprS/JkT8KKCaSsyViaIizrnF4YTQac/FC+A+7BUdg6xil0FI1xMipHQ/Z+nSwMT2ueeRThApNgufz66qw=
addons:
  coverity_scan:
    project:
      name: daniel-dressler/ippusbxd
      description: IPP over USB daemon driver for linux
    notification_email: danieru.dressler@gmail.com
    build_command_prepend: 
    build_command: make
    branch_pattern: master
